
# GitHub Actions workflow to build and deploy to Firebase Hosting
# when code is pushed to the 'demo' branch.

name: Deploy to Firebase Hosting (Demo)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js project for static export
        run: npm run build # This will generate the 'out' directory

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}'
          project_id: '${{ secrets.FIREBASE_PROJECT_ID }}' # Explicitly set project_id for ADC

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks # Enable web frameworks support if needed by your firebase-tools version
          FIREBASE_TOKEN: ${{ steps.auth.outputs.token }} # Firebase CLI can use this token directly
